### PR TITLE
Added two paragraphs 

### PR DESCRIPTION
**Pull request by jackhazard00**
Added getting water to your homes and Dryvilles first water works #[1]

### CODE REVIEW

**Review by abnerbog — APPROVED** [review]
You're all set to move on to the next step!

**Comment by jackhazard00** [comment]
Hey Abner, I just finished step 9 where I closed the loop between the main
repo and my local copy.

**Comment by abnerbog** [comment]
Thanks for the heads up Jack -- you are good to keep moving !

**Comment by jackhazard00** [comment]
Hello Abner I have arrived at step 11, it says I need to ping you again.

**Comment by jackhazard00** [comment]
Hello Abner I have arrived at step 11, it says I need to ping you again.

**Comment by abnerbog** [comment]
Thanks Jack ! You are all set to move to the next section.

**Comment by jackhazard00** [comment]
Hello Abner I have completed the second pull request.

**Pull request merged**
